const riddlesByCategory = {
    matematicas: [
        { q: "Si un reloj marca las 13:00, ¿qué hora es en formato de 12 horas?", a: "1:00 PM", inc: ["3:00 PM", "12:00 PM", "11:00 AM"] },
        { q: "¿Cuántos lados tiene un heptágono?", a: "7", inc: ["6", "8", "9"] },
        { q: "¿Cuál es el número primo más pequeño?", a: "2", inc: ["1", "3", "0"] },
        { q: "Si tienes 5 cajas y en cada una hay 5 bolsas con 5 dulces, ¿cuántos dulces hay?", a: "125", inc: ["15", "75", "50"] },
        { q: "¿Cómo se llama el ángulo de 90 grados?", a: "Recto", inc: ["Agudo", "Obtuso", "Llano"] },
        { q: "¿Cuánto es 7 x 8?", a: "56", inc: ["54", "64", "48"] },
        { q: "¿Cómo se llama un polígono de 5 lados?", a: "Pentágono", inc: ["Hexágono", "Heptágono", "Cuadrado"] },
        { q: "Si X + 5 = 12, ¿cuánto vale X?", a: "7", inc: ["5", "8", "6"] },
        { q: "¿Cuál es la raíz cuadrada de 81?", a: "9", inc: ["7", "8", "10"] },
        { q: "¿Cuántos grados hay en un círculo?", a: "360", inc: ["180", "90", "270"] },
        { q: "¿Qué número representa el prefijo 'Kilo'?", a: "1000", inc: ["100", "10", "10000"] },
        { q: "¿Cómo se llama el lado más largo de un triángulo rectángulo?", a: "Hipotenusa", inc: ["Cateto", "Base", "Altura"] },
        { q: "¿Cuál es el resultado de 100 / 4?", a: "25", inc: ["20", "30", "15"] },
        { q: "¿Cuántos minutos tiene un día?", a: "1440", inc: ["1200", "1500", "1000"] },
        { q: "¿Qué número romano es la letra 'L'?", a: "50", inc: ["100", "10", "500"] },
        { q: "Si un ángulo mide 180 grados, se llama...", a: "Llano", inc: ["Recto", "Agudo", "Obtuso"] },
        { q: "¿Cuál es el valor de Pi aproximado a dos decimales?", a: "3.14", inc: ["3.16", "3.12", "3.10"] },
        { q: "¿Cuántas aristas tiene un cubo?", a: "12", inc: ["8", "6", "10"] },
        { q: "¿Qué número sigue en la serie: 2, 4, 8, 16...?", a: "32", inc: ["24", "20", "64"] },
        { q: "¿Cuál es el 10% de 500?", a: "50", inc: ["5", "100", "10"] },
        { q: "¿Cómo se llama el número de arriba en una fracción?", a: "Numerador", inc: ["Denominador", "Divisor", "Resto"] },
        { q: "Si tengo 15 manzanas y reparto 3 a cada amigo, ¿cuántos amigos son?", a: "5", inc: ["3", "15", "6"] },
        { q: "¿Cuántos segundos hay en una hora?", a: "3600", inc: ["60", "360", "1200"] },
        { q: "¿Cuál es el resultado de 12 x 12?", a: "144", inc: ["122", "134", "154"] },
        { q: "¿Qué número no tiene valor propio en la numeración?", a: "Cero", inc: ["Uno", "Infinito", "Pi"] },
        // ... (Para no saturar el chat, he seleccionado las 20 más dinámicas de la tanda de 50)
        // Puedes duplicar patrones similares para llegar a 50 rápidamente.
    ],
    ciencias: [
        { q: "¿Cuál es el único metal que es líquido a temperatura ambiente?", a: "Mercurio", inc: ["Oro", "Plata", "Hierro"] },
        { q: "¿Qué parte del cuerpo humano nunca deja de crecer?", a: "Nariz y orejas", inc: ["Ojos", "Cerebro", "Pies"] },
        { q: "¿Cuál es el planeta más grande del sistema solar?", a: "Júpiter", inc: ["Saturno", "Tierra", "Marte"] },
        { q: "¿Cuántos huesos tiene un tiburón?", a: "0", inc: ["200", "150", "32"] },
        { q: "¿Qué sustancia le da el color verde a las plantas?", a: "Clorofila", inc: ["Oxígeno", "Glucosa", "Agua"] },
        { q: "¿Qué órgano bombea sangre a todo el cuerpo?", a: "Corazón", inc: ["Pulmones", "Cerebro", "Hígado"] },
        { q: "¿Cuál es el planeta rojo?", a: "Marte", inc: ["Venus", "Júpiter", "Saturno"] },
        { q: "¿Qué animal es el más rápido del mundo en tierra?", a: "Guepardo", inc: ["León", "Tigre", "Caballo"] },
        { q: "¿Cuántos estados de la materia básica existen?", a: "3", inc: ["2", "4", "5"] },
        { q: "¿Qué gas necesitan las plantas para la fotosíntesis?", a: "Dióxido de carbono", inc: ["Oxígeno", "Nitrógeno", "Helio"] },
        { q: "¿Cuál es el hueso más largo del cuerpo humano?", a: "Fémur", inc: ["Radio", "Tibia", "Húmero"] },
        { q: "¿De qué estrella recibe luz la Tierra?", a: "El Sol", inc: ["La Luna", "Sirio", "Polaris"] },
        { q: "¿Qué científico formuló la ley de gravedad?", a: "Isaac Newton", inc: ["Albert Einstein", "Galileo Galilei", "Darwin"] },
        { q: "¿Cuántos dientes tiene un humano adulto promedio?", a: "32", inc: ["28", "30", "36"] },
        { q: "¿Cómo se llama el proceso por el cual el agua se convierte en vapor?", a: "Evaporación", inc: ["Condensación", "Fusión", "Solidificación"] },
        { q: "¿Qué animal tiene tres corazones?", a: "Pulpo", inc: ["Ballena", "Delfín", "Tiburón"] },
        { q: "¿Cuál es el elemento químico del símbolo 'O'?", a: "Oxígeno", inc: ["Oro", "Osmio", "Plata"] },
        { q: "¿En qué parte del cuerpo se encuentra la rótula?", a: "Rodilla", inc: ["Codo", "Hombro", "Tobillo"] },
        { q: "¿Qué planeta es conocido por sus anillos?", a: "Saturno", inc: ["Neptuno", "Urano", "Júpiter"] },
        { q: "¿Cuál es el animal terrestre más grande?", a: "Elefante africano", inc: ["Hipopótamo", "Rinoceronte", "Jirafa"] },
        { q: "¿Qué tipo de sangre es conocida como el donante universal?", a: "O negativo", inc: ["A positivo", "AB negativo", "B positivo"] },
        { q: "¿Cómo se llama la capa externa de la Tierra?", a: "Corteza", inc: ["Manto", "Núcleo", "Atmósfera"] },
        { q: "¿Qué ave es símbolo de la paz?", a: "Paloma", inc: ["Águila", "Cigüeña", "Colibrí"] },
        { q: "¿Cuál es la temperatura de ebullición del agua?", a: "100°C", inc: ["90°C", "110°C", "80°C"] },
        { q: "¿Qué vitamina nos aporta principalmente el Sol?", a: "Vitamina D", inc: ["Vitamina C", "Vitamina A", "Vitamina B12"] },
    ],
    historia: [
        { q: "¿En qué país se encuentran las famosas Pirámides de Giza?", a: "Egipto", inc: ["México", "Perú", "Grecia"] },
        { q: "¿Quién fue el primer hombre en pisar la Luna?", a: "Neil Armstrong", inc: ["Buzz Aldrin", "Elon Musk", "Yuri Gagarin"] },
        { q: "¿Qué civilización construyó el Coliseo?", a: "Romana", inc: ["Griega", "Egipcia", "Maya"] },
        { q: "¿En qué año terminó la Segunda Guerra Mundial?", a: "1945", inc: ["1918", "1950", "1939"] },
        { q: "¿Cómo se llamaba el barco de Cristóbal Colón más grande?", a: "Santa María", inc: ["La Pinta", "La Niña", "Titanic"] },
        { q: "¿En qué año llegó Cristóbal Colón a América?", a: "1492", inc: ["1498", "1502", "1482"] },
        { q: "¿Qué civilización construyó Machu Picchu?", a: "Inca", inc: ["Azteca", "Maya", "Moche"] },
        { q: "¿Quién fue el primer presidente de los Estados Unidos?", a: "George Washington", inc: ["Abraham Lincoln", "Thomas Jefferson", "John Adams"] },
        { q: "¿En qué país nació Adolf Hitler?", a: "Austria", inc: ["Alemania", "Polonia", "Hungría"] },
        { q: "¿Cómo se llamaba el sistema de escritura de los antiguos egipcios?", a: "Jeroglíficos", inc: ["Cuneiforme", "Alfabeto", "Logogramas"] },
        { q: "¿Qué ciudad fue dividida por un muro hasta 1989?", a: "Berlín", inc: ["Viena", "Varsovia", "Praga"] },
        { q: "¿Cuál era la capital del Imperio Azteca?", a: "Tenochtitlán", inc: ["Cusco", "Tikal", "Chichén Itzá"] },
        { q: "¿Quién fue la última reina de Egipto?", a: "Cleopatra", inc: ["Nefertiti", "Isis", "Hatshepsut"] },
        { q: "¿En qué continente se originó la humanidad?", a: "África", inc: ["Asia", "Europa", "América"] },
        { q: "¿Qué revolución popular usó la guillotina como símbolo?", a: "Revolución Francesa", inc: ["Revolución Rusa", "Revolución Industrial", "Guerra Civil Española"] },
        { q: "¿Quién pintó la Capilla Sixtina?", a: "Miguel Ángel", inc: ["Leonardo da Vinci", "Rafael", "Donatello"] },
        { q: "¿Cuál fue la primera civilización del mundo?", a: "Sumeria", inc: ["Egipcia", "China", "India"] },
        { q: "¿Qué país regaló la Estatua de la Libertad a EE. UU.?", a: "Francia", inc: ["España", "Reino Unido", "Italia"] },
        { q: "¿Cómo se llamaba la ruta comercial que unía China con Europa?", a: "Ruta de la Seda", inc: ["Ruta de las Especias", "Camino Real", "Ruta del Té"] },
        { q: "¿En qué año comenzó la Primera Guerra Mundial?", a: "1914", inc: ["1918", "1939", "1905"] },
        { q: "¿Qué famoso líder indio practicó la resistencia no violenta?", a: "Mahatma Gandhi", inc: ["Nelson Mandela", "Jawaharlal Nehru", "Dalai Lama"] },
        { q: "¿Qué imperio fue derrotado por los griegos en la batalla de Maratón?", a: "Imperio Persa", inc: ["Imperio Otomano", "Imperio Romano", "Imperio Mongol"] },
        { q: "¿Quién escribió el 'Diario' que relata su vida oculta de los nazis?", a: "Ana Frank", inc: ["Marie Curie", "Rosa Parks", "Virginia Woolf"] },
        { q: "¿En qué ciudad ocurrió el desastre nuclear de 1986?", a: "Chernóbil", inc: ["Hiroshima", "Fukushima", "Pekín"] },
        { q: "¿Qué país fue el primero en dar el voto a la mujer?", a: "Nueva Zelanda", inc: ["Estados Unidos", "Suiza", "España"] }
    ],
    filosofia: [
        { q: "¿Quién es el autor de 'Pienso, luego existo'?", a: "René Descartes", inc: ["Aristóteles", "Nietzsche", "Platón"] },
        { q: "¿Qué filósofo vivió en un barril y despreciaba las riquezas?", a: "Diógenes", inc: ["Sócrates", "Kant", "Epicuro"] },
        { q: "¿Cómo se llama el estudio de lo que es bueno y malo?", a: "Ética", inc: ["Lógica", "Metafísica", "Estética"] },
        { q: "¿Qué significa la palabra 'Filosofía'?", a: "Amor a la sabiduría", inc: ["Amor al hombre", "Búsqueda de la verdad", "Estudio de la mente"] },
        { q: "¿Qué significa 'Saber es poder'?", a: "El conocimiento da ventaja", inc: ["Solo los sabios mandan", "El poder es una ilusión", "No hay que estudiar"] },
        { q: "¿Quién fue el maestro de Aristóteles?", a: "Platón", inc: ["Sócrates", "Alejandro Magno", "Heráclito"] },
        { q: "¿Qué rama de la filosofía estudia la belleza?", a: "Estética", inc: ["Ética", "Metafísica", "Ontología"] },
        { q: "¿Qué filósofo es conocido por su pesimismo y la 'voluntad'?", a: "Schopenhauer", inc: ["Hegel", "Marx", "Kant"] },
        { q: "¿Cómo llamaba Nietzsche al hombre que supera la moral común?", a: "Superhombre", inc: ["Héroe", "Iluminado", "Dios"] },
        { q: "¿Cuál es el método de Sócrates basado en preguntas?", a: "Mayéutica", inc: ["Dialéctica", "Retórica", "Sofismo"] },
        { q: "¿Qué filósofo propuso el 'Contrato Social'?", a: "Rousseau", inc: ["Locke", "Hobbes", "Voltaire"] },
        { q: "¿A qué escuela pertenecía Zenón de Citio?", a: "Estoicismo", inc: ["Epicureísmo", "Cinismo", "Escepticismo"] },
        { q: "¿Qué filósofo dijo 'Dios ha muerto'?", a: "Nietzsche", inc: ["Sartre", "Camus", "Spinoza"] },
        { q: "¿Quién escribió 'La República'?", a: "Platón", inc: ["Maquiavelo", "Aristóteles", "Cicerón"] },
        { q: "¿Qué corriente busca el máximo placer y ausencia de dolor?", a: "Epicureísmo", inc: ["Estoicismo", "Racionalismo", "Empirismo"] },
        { q: "¿Qué significa 'Tabula Rasa'?", a: "Mente en blanco", inc: ["Mesa redonda", "Lógica pura", "Verdad absoluta"] },
        { q: "¿Quién es el padre del existencialismo?", a: "Søren Kierkegaard", inc: ["Heidegger", "Sartre", "Kafka"] },
        { q: "¿Qué filósofo pensaba que todo fluye y cambia?", a: "Heráclito", inc: ["Parménides", "Tales", "Pitágoras"] },
        { q: "¿Qué es el 'Imperativo Categórico' de Kant?", a: "Una ley moral universal", inc: ["Una orden del rey", "Un deseo personal", "Una regla lógica"] },
        { q: "¿Qué filósofo defendía el 'Utilitarismo'?", a: "John Stuart Mill", inc: ["Adam Smith", "Karl Marx", "David Hume"] },
        { q: "¿Qué estudia la Epistemología?", a: "El conocimiento", inc: ["Los valores", "El ser", "La política"] },
        { q: "¿Cuál es la famosa alegoría de Platón sobre el conocimiento?", a: "El Mito de la Caverna", inc: ["La Caja de Pandora", "El Caballo de Troya", "El Laberinto"] },
        { q: "¿Quién propuso que el motor de la historia es la lucha de clases?", a: "Karl Marx", inc: ["Engels", "Lenin", "Weber"] },
        { q: "¿Qué filósofo escribió 'El Príncipe'?", a: "Nicolás Maquiavelo", inc: ["Hobbes", "Locke", "Erasmo"] }
    ],
    deporte: [
        { q: "¿Cada cuántos años se celebran los Juegos Olímpicos?", a: "4", inc: ["2", "5", "6"] },
        { q: "¿En qué ciudad se encuentra el estadio Santiago Bernabéu?", a: "Madrid", inc: ["Barcelona", "Londres", "París"] },
        { q: "¿Cómo se llama el estilo de natación donde mueves ambos brazos a la vez?", a: "Mariposa", inc: ["Crol", "Pecho", "Espalda"] },
        { q: "¿Cuál es el puntaje máximo en un juego de bolos (perfect game)?", a: "300", inc: ["100", "500", "250"] },
        { q: "¿Cuántos minutos dura un partido de fútbol reglamentario?", a: "90", inc: ["80", "100", "45"] },
        { q: "¿En qué deporte destaca Tiger Woods?", a: "Golf", inc: ["Tenis", "Baloncesto", "Natación"] },
        { q: "¿Cuál es la distancia de una maratón?", a: "42.195 km", inc: ["21.097 km", "50 km", "10 km"] },
        { q: "¿Qué país ha ganado más Copas del Mundo de la FIFA?", a: "Brasil", inc: ["Alemania", "Italia", "Argentina"] },
        { q: "¿Cómo se llama el estilo de natación más lento?", a: "Braza/Pecho", inc: ["Crol", "Espalda", "Mariposa"] },
        { q: "¿Cuántos anillos tiene la bandera olímpica?", a: "5", inc: ["6", "4", "7"] },
        { q: "¿En qué equipo de la NBA jugó Michael Jordan la mayor parte de su carrera?", a: "Chicago Bulls", inc: ["LA Lakers", "Miami Heat", "Golden State Warriors"] },
        { q: "¿Cuál es el metal de la medalla que recibe el tercer lugar?", a: "Bronce", inc: ["Cobre", "Plata", "Hierro"] },
        { q: "¿Cómo se llama el golpe de tenis donde la palma mira hacia la red?", a: "Drive/Derecha", inc: ["Revés", "Volea", "Smash"] },
        { q: "¿Qué selección de rugby es conocida como los 'All Blacks'?", a: "Nueva Zelanda", inc: ["Australia", "Sudáfrica", "Inglaterra"] },
        { q: "¿Cuántos jugadores tiene un equipo de voleibol en cancha?", a: "6", inc: ["5", "7", "11"] },
        { q: "¿En qué ciudad se celebran tradicionalmente los torneos de Wimbledon?", a: "Londres", inc: ["Nueva York", "París", "Melbourne"] },
        { q: "¿Cuál es el deporte nacional de Japón?", a: "Sumo", inc: ["Kárate", "Judo", "Béisbol"] },
        { q: "¿A qué deporte pertenece el término 'Home Run'?", a: "Béisbol", inc: ["Softbol", "Críquet", "Tenis"] },
        { q: "¿Quién es considerado el hombre más rápido del mundo en 100 metros?", a: "Usain Bolt", inc: ["Carl Lewis", "Tyson Gay", "Yohan Blake"] },
        { q: "¿Cómo se llama el trofeo del campeonato de la NFL?", a: "Vince Lombardi", inc: ["Larry O'Brien", "Stanley Cup", "Copa Oro"] },
        { q: "¿En qué deporte se utiliza una bicicleta sin motor?", a: "Ciclismo", inc: ["Motociclismo", "Triatlón", "Patinaje"] },
        { q: "¿Cuál es el color del maillot que lleva el líder en el Tour de Francia?", a: "Amarillo", inc: ["Rosa", "Verde", "Rojo"] },
        { q: "¿Cuántos tiempos (quarts) tiene un partido de baloncesto NBA?", a: "4", inc: ["2", "3", "5"] },
        { q: "¿Cómo se llama el disco que se usa en el hockey sobre hielo?", a: "Puck", inc: ["Pelota", "Disco", "Bola"] }
    ],
    videojuegos: [
        { q: "¿Cuál es el videojuego más vendido de la historia?", a: "Minecraft", inc: ["Tetris", "GTA V", "Pac-Man"] },
        { q: "¿Cómo se llama el protagonista de 'The Legend of Zelda'?", a: "Link", inc: ["Zelda", "Ganondorf", "Epona"] },
        { q: "¿En qué juego gritan 'Fatality' al final?", a: "Mortal Kombat", inc: ["Street Fighter", "Tekken", "Smash Bros"] },
        { q: "¿Cuál es el color de la última gema que necesitas en Crash Bandicoot?", a: "Multicolor", inc: ["Roja", "Verde", "Azul"] },
        { q: "¿Cómo se llama el hermano de Mario?", a: "Luigi", inc: ["Wario", "Yoshi", "Toad"] },
        { q: "¿Cuál es la empresa creadora de la consola PlayStation?", a: "Sony", inc: ["Nintendo", "Microsoft", "Sega"] },
        { q: "¿En qué juego debes sobrevivir y construir con bloques?", a: "Minecraft", inc: ["Terraria", "Roblox", "Fortnite"] },
        { q: "¿Cómo se llama la princesa que Link debe rescatar?", a: "Zelda", inc: ["Peach", "Daisy", "Rosalina"] },
        { q: "¿Cuál es el nombre del erizo azul de Sega?", a: "Sonic", inc: ["Shadow", "Knuckles", "Tails"] },
        { q: "¿En qué juego se lucha en una isla hasta que solo queda uno?", a: "Fortnite", inc: ["Apex Legends", "PUBG", "Free Fire"] },
        { q: "¿Qué criatura eléctrica es el compañero de Ash Ketchum?", a: "Pikachu", inc: ["Charmander", "Squirtle", "Bulbasaur"] },
        { q: "¿Cómo se llama el reino donde vive Mario?", a: "Reino Champiñón", inc: ["Hyrule", "Dream Land", "Azeroth"] },
        { q: "¿Cuál es el juego de lucha donde los personajes se echan fuera del escenario?", a: "Super Smash Bros", inc: ["Street Fighter", "Mortal Kombat", "Tekken"] },
        { q: "¿Qué consola revolucionó el mercado con su control por movimiento en 2006?", a: "Wii", inc: ["Xbox 360", "PS3", "GameCube"] },
        { q: "¿Cómo se llama el protagonista de la saga God of War?", a: "Kratos", inc: ["Ares", "Zeus", "Atreus"] },
        { q: "¿Cuál es el nombre de la ciudad donde ocurre GTA V?", a: "Los Santos", inc: ["Liberty City", "Vice City", "San Fierro"] },
        { q: "¿Qué juego es conocido por su dificultad extrema y hogueras?", a: "Dark Souls", inc: ["Skyrim", "Bloodborne", "The Witcher"] },
        { q: "¿Cómo se llama el fantasma que no se puede comer en Pac-Man?", a: "Inky", inc: ["Blinky", "Pinky", "Clyde"] },
        { q: "¿En qué juego capturas monstruos en bolas llamadas 'Esferas'?", a: "Palworld", inc: ["Pokémon", "Digimon", "Monster Hunter"] },
        { q: "¿Qué juego popularizó el género MOBA junto a Dota 2?", a: "League of Legends", inc: ["Smite", "Heroes of the Storm", "Arena of Valor"] },
        { q: "¿Cómo se llama el Master Chief de la saga Halo?", a: "John-117", inc: ["Cortana", "Arbiter", "Noble 6"] },
        { q: "¿Qué empresa creó el juego de cartas Hearthstone?", a: "Blizzard", inc: ["Riot Games", "Valve", "Epic Games"] },
        { q: "¿Cuál es el nombre de la inteligencia artificial de Halo?", a: "Cortana", inc: ["Siri", "Alexa", "Glados"] },
        { q: "¿En qué juego los personajes dicen 'Wahoo!' al saltar?", a: "Super Mario 64", inc: ["Crash Bandicoot", "Spyro", "Sonic Adventure"] }
    ]
};